providers = ["python"]

[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "source /app/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "source /app/venv/bin/activate && python3 server.py"

